# Copyright 2018 REMME
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

swagger: '2.0'

info:
  title: 'REMME Core REST API'
  version: '0.1'

consumes:
  - application/json
produces:
  - application/json

paths:
  /token:
    post:
      summary: Send tokens from the current user to another user
      parameters:
        - name: payload
          in: body
          required: true
          schema:
            properties:
              pubkey_to:
                description: The hex-encoded public key of the user to send tokens to
                type: string
              amount:
                description: The amount of tokens to be sent
                type: integer
            required:
              - pubkey_to
              - amount
      responses:
        200:
          $ref: '#/responses/200BatchSubmitted'
        500:
          $ref: '#/responses/500GeneralError'
  /token/{pubkey_user}:
    get:
      summary: Retrieve the amount of tokens for the specified user
      parameters:
        - name: pubkey_user
          description: The public key of the user to check the amount of tokens
          in: path
          type: string
          required: true
      responses:
        200:
          description: The amount of tokens for the specified user
          schema:
            properties:
              pubkey:
                type: string
                description: The hex-encoded public key of the user
              balance:
                type: integer
                description: The amount of tokens on user's balance
            required:
              - pubkey
              - balance
        500:
          $ref: '#/responses/500GeneralError'
  /certificate:
    put:
      summary: Generate and register a new certificate
      parameters:
        - name: payload
          in: body
          required: true
          schema:
            properties:
              validity:
                description: The amount of days certificate is valid for
                type: integer
              passphrase:
                description: passphrase as a second factor encryption
                type: string
              country_name:
                description: Country code (2 symbols)
                type: string
              locality_name:
                description: Locality name
                type: string
              common_name:
                description: Common name
                type: string
              name:
                description: Given name of the certificate user
                type: string
              surname:
                description: Surname of the certificate user
                type: string
              email:
                description: Email of the certificate user
                type: string
            required:
              - validity
      responses:
        200:
          description: A new certificate was generated and the registration transaction was submitted
          schema:
            properties:
              batch_id:
                type: string
                description: The hex-encoded identifier of the batch in which the transaction was submitted
              certificate:
                type: string
                description: PEM encoded certificate
              privkey:
                type: string
                description: PEM encoded private key
            required:
              - batch_id
              - certificate
              - privkey
        500:
          $ref: '#/responses/500GeneralError'
    delete:
      summary: Revoke a certificate
      parameters:
        - name: payload
          in: body
          required: true
          schema:
            properties:
              certificate:
                description: PEM encoded certificate file
                type: string
            required:
              - certificate
      responses:
        200:
          $ref: '#/responses/200BatchSubmitted'
        404:
          $ref: '#/responses/404NoCertificate'
        500:
          $ref: '#/responses/500GeneralError'
    post:
      summary: Check the status of the provided certificate
      parameters:
        - name: certificate
          description: PEM encoded certificate file
          in: body
          required: true
          schema:
            type: string
      responses:
        200:
          description: Certificate is registered on the REMchain
          schema:
            properties:
              revoked:
                description: Indicates if the certificate was revoked
                type: boolean
              owner_pubkey:
                description: The hex-encoded public key of the certificate owner
                type: string
            required:
              - revoked
              - owner_pubkey
        404:
          $ref: '#/responses/404NoCertificate'
        500:
          $ref: '#/responses/500GeneralError'

responses:
  200BatchSubmitted:
    description: The transaction was successfully passed to the validator
    schema:
      properties:
        batch_id:
          type: string
          description: The hex-encoded identifier of the batch in which the transaction was submitted
      required:
        - batch_id
  404NoCertificate:
    description: This certificate was not registered on REMchain
  500GeneralError:
    description: Error processing this request
    schema:
      type: string
