# Copyright 2018 REMME
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

# FIXME Circle CI doesn't support Compose format > 3.2. Upgrade when we move to Jenkins.
version: '3.2'

services:
  tests:
    container_name: remme_tests
    image: remme/remme-core-dev:latest
    network_mode: bridge
    volumes:
      - ../config/remme-client-config.toml:/config/remme-client-config.toml
    environment:
      - TEST_BIND=tcp://127.0.0.1:4004
    entrypoint: python3 -m unittest discover ./tests

  remme-tp:
    container_name: remme_tests_tp
    image: remme/remme-core-dev:latest
    network_mode: "service:tests"
    volumes:
      - ../config/remme-client-config.toml:/config/remme-client-config.toml
    environment:
      IS_TESTING: "True"
    entrypoint: python3 -m remme.tp --account --atomic-swap --pubkey
